---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
  
  - name: install sudo package
    tags: always
    package:
      name: sudo
      state: present


- hosts: all
  become: true
  roles:
    - base

 
- hosts: workstations
  become: true
  roles:
    - workstations


- hosts: dev_servers
  become: true
  roles:
    - dev_servers


- hosts: web_servers
  become: true
  roles:
    - web_servers


- hosts: db_servers
  become: yes
  roles:
    - db_servers  


- hosts: file_servers
  become: yes
  roles:
    - file_servers
