---
# Run with ansible-playbook main.yml -K
- hosts: localhost
  connection: local
  become: yes
  
  vars:
    linux_packages:
      - pv

  roles:
    - geerlingguy.apache

  tasks:
    - name: Install required packages (Debian-based)
      apt:
        name: "{{ linux_packages }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install required packages (RedHat-based)
      yum:
        name: "{{ linux_packages }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

