---
- name: Add codebase folder.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /home/takeoff/domains
    - /home/takeoff/domains/drupal7
    - /home/takeoff/domains/drupal8

- name: Make sure home directory has execute permissions.
  file:
    path: /home/takeoff
    state: directory
    mode: 0711
